# Autogenerated wrapper script for XGBoost_jll for x86_64-w64-mingw32
export libgomp, libxgboost, xgboost

JLLWrappers.@generate_wrapper_header("XGBoost")
JLLWrappers.@declare_library_product(libgomp, "libgomp-1.dll")
JLLWrappers.@declare_library_product(libxgboost, "xgboost.dll")
JLLWrappers.@declare_executable_product(xgboost)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgomp,
        "bin\\libgomp-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxgboost,
        "bin\\xgboost.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        xgboost,
        "bin\\xgboost.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
